"""Synthetic examples, deliberately labeled. No customer data."""
SAMPLES = [
    dict(title="Checkout cannot reach its database", service="checkout-api", severity="High", status="Open",
         description="Synthetic demo: customers cannot complete checkout after a configuration change.",
         logs="2026-09-24T09:12:01 INFO checkout request started\n2026-09-24T09:12:02 ERROR database ECONNREFUSED at db.internal:5432\n2026-09-24T09:12:02 ERROR checkout failed request_id=demo-101", resolution=""),
    dict(title="Orders database connection refused", service="orders-api", severity="High", status="Resolved",
         description="Synthetic historical incident: database port was incorrectly configured.",
         logs="ERROR orders database connection refused ECONNREFUSED db.internal:5433",
         resolution="Corrected the configured database port from 5433 to 5432. Verified a successful orders query and confirmed no new connection errors."),
    dict(title="Payment provider requests time out", service="payments-api", severity="Critical", status="Investigating",
         description="Synthetic demo: upstream payment responses exceed the request timeout.",
         logs="INFO payment request started\nERROR upstream timed out after 5000ms\nERROR gateway timeout payment-provider", resolution=""),
    dict(title="Payment gateway latency incident", service="payments-api", severity="High", status="Resolved",
         description="Synthetic historical incident: upstream gateway latency caused payment request timeouts.",
         logs="ERROR upstream timed out payment-provider gateway timeout",
         resolution="Confirmed provider degradation and queued safe requests with bounded backoff. Verified response latency after provider recovery; checked for duplicate payments."),
    dict(title="Report export exceeds heap limit", service="reports-worker", severity="Medium", status="Open",
         description="Synthetic demo: export worker processes a large report in memory.",
         logs="INFO export job started rows=500000\nFATAL heap out of memory\nERROR worker process exited", resolution=""),
    dict(title="Report worker memory exhaustion", service="reports-worker", severity="High", status="Resolved",
         description="Synthetic historical incident: an unbounded export batch exhausted memory.",
         logs="FATAL heap out of memory OutOfMemoryError report export",
         resolution="Changed the export to bounded batches and streamed rows to disk. Repeated the workload and verified memory remained below the worker limit."),
    dict(title="Expired token blocks profile requests", service="identity-api", severity="Medium", status="Resolved",
         description="Synthetic historical incident: cached service credential expired.",
         logs="ERROR Unauthorized token expired authentication failed",
         resolution="Renewed the service credential and corrected refresh handling. Verified valid credentials succeed and expired credentials remain rejected."),
    dict(title="Application logs fill storage", service="audit-worker", severity="High", status="Resolved",
         description="Synthetic historical incident: log retention failed and exhausted filesystem capacity.",
         logs="ERROR ENOSPC No space left on device while writing audit log",
         resolution="Archived approved old logs and repaired rotation. Verified free disk capacity and a successful audit write."),
]
