import React,{useState,useEffect} from 'react';
import {Activity,LockKeyhole,ShieldCheck} from 'lucide-react';
import {api,setCSRF} from './api';
export default function Account({children}){
 const [user,setUser]=useState(null),[ready,setReady]=useState(false),[setup,setSetup]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({name:'',username:'',password:'',code:''});
 async function bootstrap(){
  try{const status=await api('/auth/status');setSetup(status.setup_required);if(!status.setup_required){try{const r=await api('/auth/me');setUser(r.user);setCSRF(r.csrf)}catch{setUser(null)}}}
  catch(e){setError(e.message)}finally{setReady(true)}
 }
 useEffect(()=>{bootstrap();const expire=()=>{setUser(null);setCSRF('');setError('Your session expired or your access changed. Please sign in again.')};window.addEventListener('session-expired',expire);return()=>window.removeEventListener('session-expired',expire)},[]);
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const r=await api(setup?'/auth/setup':'/auth/login',{method:'POST',body:JSON.stringify(setup?form:{username:form.username,password:form.password})});setCSRF(r.csrf);setUser(r.user);setSetup(false);setForm({name:'',username:'',password:'',code:''})}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function logout(){try{await api('/auth/logout',{method:'POST',body:'{}'});setUser(null);setCSRF('')}catch(e){setError(e.message);alert(e.message)}}
 const field=k=>({value:form[k],onChange:e=>setForm({...form,[k]:e.target.value})});
 if(!ready)return <div className="empty">Opening your workspace…</div>;
 if(user)return children(user,logout);
 return <div className="auth-page"><section className="auth-story"><div className="brand"><span className="brand-icon"><Activity/></span>Resolve<span className="brand-iq">IQ</span></div><div><span className="eyebrow">INCIDENT OPERATIONS / V2</span><h1>Every incident.<br/>A clearer next step.</h1><p>Bring evidence, people, and service health into one investigation workspace.</p><div className="auth-features"><span><ShieldCheck size={18}/>Role-based team access</span><span><Activity size={18}/>Live local service monitoring</span><span><LockKeyhole size={18}/>Private workspace sessions</span></div></div><small>Local portfolio edition · Synthetic demo service</small></section><section className="auth-card"><span className="eyebrow">{setup?'FIRST-TIME SETUP':'WELCOME BACK'}</span><h2>{setup?'Create your workspace':'Sign in to ResolveIQ'}</h2><p>{setup?'Create your administrator account. Open SETUP_CODE.txt in your project folder and copy the code on its second line. This file appears after the server starts.':'Use an account created by your workspace administrator.'}</p>{error&&<div role="alert" className="error">{error}</div>}<form onSubmit={submit}>{setup&&<><label>Your name<input autoComplete="name" required minLength={2} maxLength={80} {...field('name')}/></label><label>Setup code from SETUP_CODE.txt<input autoComplete="off" spellCheck={false} required {...field('code')}/></label></>}<label>Username (no @ or spaces)<input autoComplete="username" placeholder="amogha_cv" pattern="[a-zA-Z0-9_.\-]{3,40}" title="Use 3–40 letters, numbers, dots, underscores or dashes. Email addresses are not supported." required minLength={3} maxLength={40} {...field('username')}/></label><label>Password<input type="password" autoComplete={setup?'new-password':'current-password'} required minLength={setup?15:1} maxLength={128} {...field('password')}/></label>{setup&&<p className="muted">Use a memorable passphrase of at least 15 characters. There is no default password.</p>}<button className="primary full" disabled={busy}>{busy?'Please wait…':setup?'Create administrator':'Sign in'}</button></form><p className="method-note">Runs on your computer. Keep the server terminal open while using the app.</p></section></div>
}
